### ISSUE TITLE
Bad SHA256 with 

### ISSUE THREAD

**Issue by PierreR** [adisbladis/vgo2nix#18]
I am trying to use `vgo2nix` (master branch) with https://github.com/atlassian/terraform-provider-artifactory/blob/master/go.mod but I have got the following error:

```
Finished fetching github.com/Azure/azure-sdk-for-go
Fetching github.com/prometheus/procfs
panic: Error processing import path "github.com/Azure/azure-sdk-for-go": Bad SHA256 for repo https://github.com/Azure/azure-sdk-for-go with rev v10.3.0-beta+incompatible

goroutine 1 [running]:
main.main()
	/build/go/src/github.com/adisbladis/vgo2nix/main.go:239 +0x61e

```
It is `github.com/hashicorp/terraform v0.11.13` that causes the issue.

Any idea ?
Thanks

**Comment by takeda** [comment]
Got similar error when trying to use `vgo2nix` on https://github.com/buzzfeed/sso

```
Fetching git.apache.org/thrift.git: (git.apache.org/thrift 2566ecd5d999)
Finished fetching git.apache.org/thrift.git
panic: Error processing import path "git.apache.org/thrift.git": Bad SHA256 for repo git.apache.org/thrift with rev 2566ecd5d999

goroutine 1 [running]:
main.main()
	/private/var/folders/49/2733c3m96nngsh36rfn8x38h0000gp/T/nix-build-vgo2nix-git.drv-0/go/src/github.com/adisbladis/vgo2nix/main.go:245 +0x67d
```

**Comment by takeda** [comment]
Looks like in your case vgo2nix shouldn't add `+incompatible` to the rev.

In my case it fails because repo is not accessible?

```
$ nix-prefetch-git --fetch-submodules --url https://git.apache.org/thrift.git --rev 2566ecd5d999
Initialized empty Git repository in /private/var/folders/49/2733c3m96nngsh36rfn8x38h0000gp/T/git-checkout-tmp-n4Mf1CgX/thrift-2566ecd/.git/
fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection refused
fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection refused
Unable to checkout 2566ecd5d999 from https://git.apache.org/thrift.git.
```

I don't understand why it is being fetched though, it is not listed in go.mod.

**Comment by takeda** [comment]
So in my case it looks like that single repo is just not available right now. After I cleaned up the GOPATH go also had problem fetching the repo. It would be useful if the error message was changed to something more meaningful, like "unable to fetch contents of a repo?" Looks like code rejects "0sjjj9z1dhilhpc8pq4154czrb79z9cm044jvn75kxcjv6v5l2m5" hash, because that's a hash of an empty directory.

It would also be great if vgo2nix could simply reuse the repos in GOPATH instead refetching them over again.
