### ISSUE TITLE
Segfault when running

### ISSUE THREAD

**Issue by matthiasbeyer** [adisbladis/vgo2nix#23]
```
Encountered error: Error processing import path "github.com/Unknwon/i18n": Bad SHA256 for repo https://github.com/Unknwon/i18n with rev b64d33658966
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x66d613]

goroutine 1 [running]:
main.getPackages(0x708401, 0x1, 0xc0000ad230, 0x0, 0x17, 0xc0000b3088, 0xc0000a6e90, 0x10)
	/build/go/src/github.com/adisbladis/vgo2nix/main.go:196 +0x3e3
main.main()
	/build/go/src/github.com/adisbladis/vgo2nix/main.go:230 +0x217
```

When running in the https://github.com/writeas/writefreely repository.

What can I do?

**Comment by matthiasbeyer** [comment]
Any hints?
